apiVersion: v1
kind: Config
clusters:
- name: microk8s
  cluster:
    certificate-authority: /var/snap/microk8s/current/certs/ca.crt
    server: https://127.0.0.1:16443
users:
- name: test_user1
  user:
    client-certificate: ./user.crt
    client-key: ./user.key
contexts:
- name: microk8s-test_user1
  context:
    cluster: microk8s
    user: test_user1
current-context: microk8s-test_user1
