apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    app: web
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
