apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "$(date) запись от busybox" >> /data/output.txt;
                sleep 5;
              done
          volumeMounts:
            - name: data
              mountPath: /data
        - name: multitool
          image: wbitt/network-multitool:latest
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: local-pvc
