apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-{{ .Release.Name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: backend
        env: {{ .Values.env }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
