apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-{{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: frontend
        env: {{ .Values.env }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
